In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import sklearn as sk

In [5]:
df = pd.read_csv('diamonds.csv')
df.head()

Unnamed: 0  carat        cut  cut_ord color clarity  clarity_ord  price
0           1   0.51    Premium        4     F     VS1            4   1749
1           2   2.25       Fair        1     G      I1            1   7069
2           3   0.70  Very Good        3     E     VS2            5   2757
3           4   0.47       Good        2     F     VS1            4   1243
4           5   0.30      Ideal        5     G    VVS1            7    789

WELCOME TO MACHINE LEARNING


In [9]:
x=pd.get_dummies(x)
x.head()

carat  cut_Fair  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  color_D  \
0   0.51         0         0          0            1              0        0   
1   2.25         1         0          0            0              0        0   
2   0.70         0         0          0            0              1        0   
3   0.47         0         1          0            0              0        0   
4   0.30         0         0          1            0              0        0   

   color_E  color_F  color_G  ...  color_I  color_J  clarity_I1  clarity_IF  \
0        0        1        0  ...        0        0           0           0   
1        0        0        1  ...        0        0           1           0   
2        1        0        0  ...        0        0           0           0   
3        0        1        0  ...        0        0           0           0   
4        0        0        1  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0            0            1            0             0   
1            0            0            0            0             0   
2            0            0            0            1             0   
3            0            0            1            0             0   
4            0            0            0            0             1   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 21 columns]

In [ ]:
#scaling our data

In [11]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler=StandardScaler()
x=scaler.fit_transform(x)
x

array([[-0.6080254 , -0.17586311, -0.3162869 , ..., -0.54205944,
        -0.26921751, -0.32210675],
       [ 3.05785977,  5.6862407 , -0.3162869 , ..., -0.54205944,
        -0.26921751, -0.32210675],
       [-0.20772759, -0.17586311, -0.3162869 , ...,  1.84481613,
        -0.26921751, -0.32210675],
       ...,
       [ 0.71927785, -0.17586311, -0.3162869 , ...,  1.84481613,
        -0.26921751, -0.32210675],
       [ 0.44538988, -0.17586311, -0.3162869 , ...,  1.84481613,
        -0.26921751, -0.32210675],
       [ 2.0465811 , -0.17586311, -0.3162869 , ...,  1.84481613,
        -0.26921751, -0.32210675]])

In [14]:
from sklearn.model_selection import train_test_split


In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,target,test_size=0.3,random_state=40)

In [ ]:
#fit the data into our model

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model= LinearRegression()

In [ ]:
#now fit the data together

In [19]:
model.fit(x_train,y_train)

LinearRegression()

In [21]:
print(model.intercept_)
print(model.coef_)

3932.747782603237
[ 4.20638502e+03 -1.54715716e+13 -2.60772438e+13 -4.44232278e+13
 -3.95735784e+13 -3.77939168e+13 -5.19647375e+14 -6.04376982e+14
 -5.98778561e+14 -6.38036289e+14 -5.66568415e+14 -4.73963164e+14
 -3.48750390e+14  3.04298999e+14  4.68799347e+14  1.12028619e+15
  9.83678691e+14  9.39116828e+14  1.09595715e+15  6.56656487e+14
  7.63398638e+14]


In [ ]:
#the R2

In [23]:
print(model.score (x_train,y_train))

0.91573450528943


In [ ]:
#checking the prediction

In [25]:
prediction=model.predict(x_test)
prediction

array([1610.4977826, 2439.7477826, 4807.9977826, ..., 6137.2477826,
       4665.2477826, 6706.2477826])

In [27]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [ ]:
#checking MAE AND MSE

In [29]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [30]:
print(score)
print(MAE)
print(MSE)
print(RMSE)

0.9083961222737925
798.3680989774275
1345064.49302523
1159.769155058553


In [31]:
ds= pd.read_csv('new-diamonds.csv')
ds.head()

Unnamed: 0  carat        cut  cut_ord color clarity  clarity_ord
0           1   1.22    Premium        4     G     SI1            3
1           2   1.01       Good        2     G     VS2            5
2           3   0.71  Very Good        3     I     VS2            5
3           4   1.01      Ideal        5     D     SI2            2
4           5   0.27      Ideal        5     H    VVS2            6

In [37]:
k=ds.drop(['Unnamed: 0','clarity_ord','cut_ord'], axis=1)
k.head()

carat        cut color clarity
0   1.22    Premium     G     SI1
1   1.01       Good     G     VS2
2   0.71  Very Good     I     VS2
3   1.01      Ideal     D     SI2
4   0.27      Ideal     H    VVS2

In [39]:
k=pd.get_dummies(k)
k.head()

carat  cut_Fair  cut_Good  cut_Ideal  cut_Premium  cut_Very Good  color_D  \
0   1.22         0         0          0            1              0        0   
1   1.01         0         1          0            0              0        0   
2   0.71         0         0          0            0              1        0   
3   1.01         0         0          1            0              0        1   
4   0.27         0         0          1            0              0        0   

   color_E  color_F  color_G  ...  color_I  color_J  clarity_I1  clarity_IF  \
0        0        0        1  ...        0        0           0           0   
1        0        0        1  ...        0        0           0           0   
2        0        0        0  ...        1        0           0           0   
3        0        0        0  ...        0        0           0           0   
4        0        0        0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            1            0            0            0             0   
1            0            0            0            1             0   
2            0            0            0            1             0   
3            0            1            0            0             0   
4            0            0            0            0             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             1  

[5 rows x 21 columns]

In [41]:
model.fit(x,target)

LinearRegression()

In [42]:
prediction=model.predict(k)
prediction

C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([-2.06197460e+15, -1.96888915e+15, -1.93119454e+15, ...,
       -2.05410733e+15, -1.95542801e+15, -2.03269510e+15])

In [43]:
ds.assign(predicted_price=prediction)

Unnamed: 0  carat        cut  cut_ord color clarity  clarity_ord  \
0              1   1.22    Premium        4     G     SI1            3   
1              2   1.01       Good        2     G     VS2            5   
2              3   0.71  Very Good        3     I     VS2            5   
3              4   1.01      Ideal        5     D     SI2            2   
4              5   0.27      Ideal        5     H    VVS2            6   
...          ...    ...        ...      ...   ...     ...          ...   
2995        2996   0.72      Ideal        5     F     SI2            2   
2996        2997   1.09    Premium        4     I     VS2            5   
2997        2998   1.05  Very Good        3     G     SI1            3   
2998        2999   0.70       Fair        1     G     SI1            3   
2999        3000   1.01  Very Good        3     F     SI1            3   

      predicted_price  
0       -2.061975e+15  
1       -1.968889e+15  
2       -1.931195e+15  
3       -1.831171e+15  
4       -1.554146e+15  
...               ...  
2995    -1.874332e+15  
2996    -1.939062e+15  
2997    -2.054107e+15  
2998    -1.955428e+15  
2999    -2.032695e+15  

[3000 rows x 8 columns]

In [44]:
from xgboost import XGBRegressor
xGB=XGBRegressor()
xGB.fit(x,target)
prediction=xGB.predict(k)
prediction

array([8527.072, 8445.646, 6882.404, ..., 7162.669, 5338.947, 7308.235],
      dtype=float32)

In [45]:
ds.assign(predicted_price=prediction)

Unnamed: 0  carat        cut  cut_ord color clarity  clarity_ord  \
0              1   1.22    Premium        4     G     SI1            3   
1              2   1.01       Good        2     G     VS2            5   
2              3   0.71  Very Good        3     I     VS2            5   
3              4   1.01      Ideal        5     D     SI2            2   
4              5   0.27      Ideal        5     H    VVS2            6   
...          ...    ...        ...      ...   ...     ...          ...   
2995        2996   0.72      Ideal        5     F     SI2            2   
2996        2997   1.09    Premium        4     I     VS2            5   
2997        2998   1.05  Very Good        3     G     SI1            3   
2998        2999   0.70       Fair        1     G     SI1            3   
2999        3000   1.01  Very Good        3     F     SI1            3   

      predicted_price  
0         8527.072266  
1         8445.646484  
2         6882.403809  
3         5880.825195  
4         4684.659180  
...               ...  
2995      5220.137695  
2996      8648.356445  
2997      7162.668945  
2998      5338.946777  
2999      7308.234863  

[3000 rows x 8 columns]